package com.hehe.db;

import com.j256.ormlite.field.DatabaseField;

import java.io.Serializable;

/* loaded from: classes.dex */
public class DynamicCorpusTable implements Serializable {
    @DatabaseField(columnName = "functionEndCircleInterval")
    public int functionEndCircleInterval;
    @DatabaseField(columnName = "functionEndCircleNum")
    public int functionEndCircleNum;
    @DatabaseField(columnName = "functionEndCircleText")
    public String functionEndCircleText;
    @DatabaseField(columnName = "functionRunningCircleInterval")
    public int functionRunningCircleInterval;
    @DatabaseField(columnName = "functionRunningCircleNum")
    public int functionRunningCircleNum;
    @DatabaseField(columnName = "functionRunningCircleText")
    public String functionRunningCircleText;
    @DatabaseField(columnName = "functionStartCircleInterval")
    public int functionStartCircleInterval;
    @DatabaseField(columnName = "functionStartCircleNum")
    public int functionStartCircleNum;
    @DatabaseField(columnName = "functionStartCircleText")
    public String functionStartCircleText;
    @DatabaseField(columnName = "functionWaitCircleInterval")
    public int functionWaitCircleInterval;
    @DatabaseField(columnName = "functionWaitCircleNum")
    public int functionWaitCircleNum;
    @DatabaseField(columnName = "functionWaitCircleText")
    public String functionWaitCircleText;
    @DatabaseField(generatedId = true)
    public Integer id;
    @DatabaseField(columnName = "movementArriveWaitPointInterval")
    public int movementArriveWaitPointInterval;
    @DatabaseField(columnName = "movementArriveWaitPointNum")
    public int movementArriveWaitPointNum;
    @DatabaseField(columnName = "movementArriveWaitPointText")
    public String movementArriveWaitPointText;
    @DatabaseField(columnName = "movementGoingChargePointInterval")
    public int movementGoingChargePointInterval;
    @DatabaseField(columnName = "movementGoingChargePointNum")
    public int movementGoingChargePointNum;
    @DatabaseField(columnName = "movementGoingChargePointText")
    public String movementGoingChargePointText;
    @DatabaseField(columnName = "movementGoingWaitPointInterval")
    public int movementGoingWaitPointInterval;
    @DatabaseField(columnName = "movementGoingWaitPointNum")
    public int movementGoingWaitPointNum;
    @DatabaseField(columnName = "movementGoingWaitPointText")
    public String movementGoingWaitPointText;
    @DatabaseField(columnName = "movementGotoChargePointInterval")
    public int movementGotoChargePointInterval;
    @DatabaseField(columnName = "movementGotoChargePointNum")
    public int movementGotoChargePointNum;
    @DatabaseField(columnName = "movementGotoChargePointText")
    public String movementGotoChargePointText;
    @DatabaseField(columnName = "movementGotoWaitPointInterval")
    public int movementGotoWaitPointInterval;
    @DatabaseField(columnName = "movementGotoWaitPointNum")
    public int movementGotoWaitPointNum;
    @DatabaseField(columnName = "movementGotoWaitPointText")
    public String movementGotoWaitPointText;
    @DatabaseField(columnName = "movementWaitPointWaitingInterval")
    public int movementWaitPointWaitingInterval;
    @DatabaseField(columnName = "movementWaitPointWaitingNum")
    public int movementWaitPointWaitingNum;
    @DatabaseField(columnName = "movementWaitPointWaitingText")
    public String movementWaitPointWaitingText;
    @DatabaseField(columnName = "targetWaitingCircleInterval")
    public int targetWaitingCircleInterval;
    @DatabaseField(columnName = "targetWaitingCircleNum")
    public int targetWaitingCircleNum;
    @DatabaseField(columnName = "targetWaitingCircleText")
    public String targetWaitingCircleText;
    @DatabaseField(columnName = "transportArriveWaitPointCircleInterval")
    public int transportArriveWaitPointCircleInterval;
    @DatabaseField(columnName = "transportArriveWaitPointCircleNum")
    public int transportArriveWaitPointCircleNum;
    @DatabaseField(columnName = "transportArriveWaitPointCircleText")
    public String transportArriveWaitPointCircleText;
    @DatabaseField(columnName = "transportFinishCircleInterval")
    public int transportFinishCircleInterval;
    @DatabaseField(columnName = "transportFinishCircleNum")
    public int transportFinishCircleNum;
    @DatabaseField(columnName = "transportFinishCircleText")
    public String transportFinishCircleText;
    @DatabaseField(columnName = "transportWaitPointWaitCircleInterval")
    public int transportWaitPointWaitCircleInterval;
    @DatabaseField(columnName = "transportWaitPointWaitCircleNum")
    public int transportWaitPointWaitCircleNum;
    @DatabaseField(columnName = "transportWaitPointWaitCircleText")
    public String transportWaitPointWaitCircleText;
    @DatabaseField(columnName = "type")
    public int type;
    @DatabaseField(columnName = "updateTime")
    public long updateTime;
}
